"""vegetables

Revision ID: 985bf24b944f
Revises: e21f7acc2d95
Create Date: 2024-08-05 11:54:39.581242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985bf24b944f'
down_revision = 'e21f7acc2d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vegetables_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_tasty', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetables_table')
    # ### end Alembic commands ###
